# Generated by Django 3.2.5 on 2021-09-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('date_of_joining', models.DateField()),
                ('today', models.DateField(auto_now_add=True)),
                ('picture', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
    ]
